CREATE TABLE MEMBER (
	ID VARCHAR(30) PRIMARY KEY,
	PW VARCHAR(30) NOT NULL
);

CREATE TABLE BOARD (
	SEQ INT(10) AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(50) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	REGDATE DATETIME DEFAULT NOW(),
	M_ID VARCHAR(30) NOT NULL,
	FOREIGN KEY M_ID REFERENCES MEMBER(ID)
);

CREATE TABLE COMMEND (
	SEQ INT(10) AUTO_INCREMENT PRIMARY KEY,
	CONTENT VARCHAR(100) NOT NULL,
	B_NUM INT(10) NOT NULL,
	U_ID VARCHAR(30) NOT NULL,
	FOREIGN KEY B_NUM REFERENCES BOARD(SEQ),
	FOREIGN KEY U_ID REFERENCES MEMBER(ID)
);